# Generated by Django 4.0.2 on 2022-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='prTypes',
            field=models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Cameras', 'Cameras')], max_length=50, verbose_name='Product type'),
        ),
    ]
