# Generated by Django 4.0.2 on 2022-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productparametrname_productparametrvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=140),
        ),
    ]
