# Generated by Django 4.0.2 on 2022-04-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_brandname_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brandName',
        ),
    ]
