# Generated by Django 4.0.2 on 2022-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandName',
            field=models.CharField(default='noname', max_length=200),
        ),
    ]
