# Generated by Django 4.0.2 on 2022-04-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='brandName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='prTypes',
            field=models.CharField(blank=True, choices=[('Smartphones', 'Smartphones'), ('Laptops', 'Laptops'), ('Cameras', 'Cameras'), ('Watch', 'Watch')], max_length=50, verbose_name='Product type'),
        ),
    ]
